### PR TITLE
Add formfeed characters, subtitles and title to initialization code.

### PR DESCRIPTION
**Pull request by sebras**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Looks good from a visual inspection.  It would be good to compare page numbers from original and new assembler listings.

**Comment by PashPaw** [comment]
Indeed.  Pulling it in though.

**Comment by sebras** [comment]
> It would be good to compare page numbers from original and new assembler listings.

I'm not sure I understand what it is you want me to do..?

**Comment by larsbrinkhoff** [comment]
> I'm not sure I understand what it is you want me to do..?

Assemble the josinit file with MACRO-10 and read the freshly generated
listing.  Check that the listing has the same number of pages as the
original listing.  E.g. to to the last page in both and see that the
page numbers match.

Next step, do this for addresses too.

**Pull request merged**
