### PR TITLE
Dab

### PR DESCRIPTION
**Pull request by dabridgham**
Use SUBTTL and ^L page breaks.  Added pages 44-47.

### CODE REVIEW

**Comment by dabridgham** [comment]
I meant, added pages 44-47.

**Comment by larsbrinkhoff** [comment]
Minor detail.  I don't think they would have used a SUBTTL on every page, just the one that starts that section.  But of course we don't know for sure.

**Comment by PashPaw** [comment]
According to the MACRO-10 documentation, SUBTTL will print the subtitle and the page its defined on and all subsequent pages until another SUBTTL pseudo-op is given.  I'm trying to confirm if this is the same in MACRO-6.

**Comment by larsbrinkhoff** [comment]
I'm more of a MIDAS person, but my impression is that MACRO-10 is just a minor update over MACRO-6 rather than a new program.  At least in the beginning.

**Comment by PashPaw** [comment]
And I believe it is but SUBTTL is barely mentioned in the MACRO-6 manuals on Bitsavers, so I'm going to assume that it's the default behavior for MACRO-6 too.

An alternate method for ^L is PAGE but the MACRO-10 documentation says that ^L is preferred.

**Comment by dabridgham** [comment]
I duplicated the SUBTTL ops because I just took them from the page number comments.  But I'm sure you're right, that's not how it should be.  I also wonder if they would have put ^L to force page breaks between places where they put SUBTTL.  Once the raw typing is done, I'm sure there will be some amount of interation with MACRO to get it to come out just right.

And I'm wondering why the SUBTTL lines don't show up in the listing.  Are they suppressed?

The MACRO-10 documentation I was looking at said PAGE and ^L are somewhat different.  PAGE increments the subpage number while ^L increments the page number.

**Comment by larsbrinkhoff** [comment]
> I also wonder if they would have put ^L to force page breaks between places where they put SUBTTL.

That sounds reasonable.

> And I'm wondering why the SUBTTL lines don't show up in the listing. Are they suppressed?

I'm wondering that too.  I'm used to seeing the SUBTTL statements in the listing.

**Pull request merged**
