### PR TITLE
Typos.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
With these updates, all page numbers are in sync.  And the final PROGRAM BREAK matches.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
@sebras, are you doing some crazy thing like typing in the symbol table?  Actually, just comparing the listing symbol table with the output from a fresh assembly would be interesting.

**Comment by sebras** [comment]
> @sebras, are you doing some crazy thing like typing in the symbol table? Actually, just comparing the listing symbol table with the output from a fresh assembly would be interesting.

I have already typed it in see `page134-149.mac`. I need to some spare time to get up to speed on ITS so I can learn how to assemble things.

**Comment by larsbrinkhoff** [comment]
Thanks, I'll compare that against a fresh listing.

**Comment by larsbrinkhoff** [comment]
Here's a crash course on assembling JOSS from ITS.  Typed in from memory, not checked.

First, get MACRO.SHR from me.  Then type this:

```
mkdir decsys
mkdir sebras
mv macro.shr decsys
cat page*.mac > sebras/su.mac
itstar cf "its"/x.dump sebras decsys
cd "its"
./start
its
$g
^Z
^\
at tu0 xdump
continue
sebras$u
dump
rewind
load crdir
*; * *

quit
:dec sys:macro
su=su
^C
```

**Comment by larsbrinkhoff** [comment]
Here's the MACRO.SHR from 1971 I have been using.  It's V47 or thereabouts.
[macro10.zip](https://github.com/PDP-10/joss-36/files/4325502/macro10.zip)

**Comment by PashPaw** [comment]
Thanks for the ITS instructions.

For those handling this on TOPS-10 5.03, it's a little bit more interesting even though it was developed on the Monitor.

At your shell prompt, use:
`$ cat page*.mac > su.mac`

From the [simh tools](https://github.com/simh/simtools) to convert it to Windows line-endings (or unix2dos) since DEC OSes use CR LF like Windows.  Rename it if you wish, but attach the converted file to simulator's paper tape reader (in this case, su.new in the same working directory as your TOPS-10 5.03 install):

`attach ptr su.new`

Run PIP after you signed into TOPS-10 and enter this:
```

.r pip


*su.mac_ptr:
```

Run MACRO-10 V47 and enter this (from here, things shouldn't diverge too much):
```

.r macro


*dsk:su,lpt:_dsk:su/o/g

```

The /o and /g switches are, more or less, compatibility switches.  The /o switch tells it to use MACRO-6's behavior for literals (instead of using a closed bracket) if there are any there and /g outputs an old-style listing.  They may or may not be needed but it's likely a good idea to use them.

Use ^C to exit MACRO (like the ITS instructions).

**Comment by larsbrinkhoff** [comment]
Do you have any MACRO switch to make a single column symbol table?

**Comment by PashPaw** [comment]
I don't see any switches that will do that.  I don't see any operations that will do that either unless XALL will do that.  Sorry. =\

**Comment by PashPaw** [comment]
Oops.  Not XALL.

Pages 250-51 give a listing of various listing operators in MACRO.

**Comment by larsbrinkhoff** [comment]
@sebras type $ as altmode, i.e. Esc.

I made a mistake above.  `dump` should be `dump^H`.

**Pull request merged**
